In [2]:
# downloading the Iris dataset from kaggle
# https://www.kaggle.com/datasets/uciml/iris
import kagglehub
path = kagglehub.dataset_download("uciml/iris")
print("Path to dataset files:", path)

Using Colab cache for faster access to the 'iris' dataset.
Path to dataset files: /kaggle/input/iris


In [3]:
#reading the data and making a dataframe
import pandas as pd
df = pd.read_csv('/kaggle/input/iris/Iris.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None


In [4]:
#simple logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x = df[['SepalLengthCm','PetalLengthCm','SepalWidthCm','PetalWidthCm']]
y = df['Species']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = LogisticRegression(max_iter=200)
model.fit(x_train,y_train)

#input = pd.DataFrame([[4.5,1.5]],columns=['SepalLengthCm','PetalLengthCm'])

predict = model.predict(x_test)
print(predict)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']


In [36]:
# Training logistic Regression model on imbalanced dataset

import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
data = np.genfromtxt('/kaggle/input/iris/Iris.csv', delimiter=',',dtype=None, names=True,encoding='utf-8')

x = data[['SepalLengthCm','PetalLengthCm','SepalWidthCm','PetalWidthCm']]
x = np.array(x.tolist())
y = data['Species']

class_0_idx = np.where(y == 'Iris-setosa')[0]
class_1_idx = np.where(y == 'Iris-versicolor')[0]
class_2_idx = np.where(y == 'Iris-virginica')[0]

class_0_subset = np.random.choice(class_0_idx, size=int(len(class_0_idx) * 0.8), replace=False)
class_1_subset = np.random.choice(class_1_idx, size=int(len(class_1_idx) * 0.2), replace=False)
class_2_subset = np.random.choice(class_2_idx, size=int(len(class_2_idx) * 0.2), replace=False)
# Combine the subsets of indices
combined_indices = np.concatenate((class_0_subset, class_1_subset,class_2_subset))
model2 = LogisticRegression()
x_train, x_test, y_train, y_test = train_test_split(x[combined_indices], y[combined_indices], test_size=0.2, random_state=42)

model2.fit(x_train, y_train)
accuracy = model2.score(x_test,y_test)
print(accuracy)

# Predict the labels for the test set
y_pred = model2.predict(x_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Classification Report (Precision, Recall, F1-score)
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

0.9166666666666666
Confusion Matrix:
[[6 0 0]
 [0 3 0]
 [0 1 2]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.75      1.00      0.86         3
 Iris-virginica       1.00      0.67      0.80         3

       accuracy                           0.92        12
      macro avg       0.92      0.89      0.89        12
   weighted avg       0.94      0.92      0.91        12

